name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go with caching
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: go.sum

      - name: Build
        run: go build -v ./...

      - name: Run unit tests with coverage
        run: SKIP_INTEGRATION=1 go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Generate HTML coverage report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Analyze coverage function report
        run: go tool cover -func=coverage.out

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: |
            coverage.out
            coverage.html

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-test  # ユニットテスト成功後に実行
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go with caching
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: go.sum

      - name: Run integration tests
        run: |
          go test -v -run "Integration" ./...


  actions-timeline:
    name: Actions Timeline
    needs: [unit-test, integration-test]

    runs-on: ubuntu-24.04
    steps:
      - uses: Kesin11/actions-timeline@v2